import {
  User,
  PencilLine,
  BanknoteArrowUp,
  BanknoteArrowDown,
  Smile,
  BadgeDollarSign,
  HatGlasses,
  ShieldUser,
  Moon,
  Star,
  Heart,
  Coffee,
  Headset,
  Cat,
  Dog,
  Panda,
  Bone,
  PawPrint,
} from "lucide-react";

export const ICONS = [
  { name: "User", icon: User },
  { name: "Smile", icon: Smile },
  { name: "BadgeDollarSign", icon: BadgeDollarSign },
  { name: "HatGlasses", icon: HatGlasses },
  { name: "ShieldUser", icon: ShieldUser },
  { name: "Moon", icon: Moon },
  { name: "Star", icon: Star },
  { name: "Heart", icon: Heart },
  { name: "Coffee", icon: Coffee },
  { name: "Headset", icon: Headset },
  { name: "Cat", icon: Cat },
  { name: "Dog", icon: Dog },
  { name: "Panda", icon: Panda },
  { name: "Bone", icon: Bone },
  { name: "PawPrint", icon: PawPrint },
];